model_checkpoint:
  _target_:  pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: null
  filename: null
  monitor: val/loss
  verbose: False
  save_top_k: 1
  mode: "min"
  auto_insert_metric_name: True
