defaults:
  - _self_
  - datamodule: datamodule.yaml
  - model: model.yaml
  - callbacks: default.yaml
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml

task_name: "train"
train: true
test: true
ckpt_path: null
seed: 42